### ISSUE TITLE
awesome tutorial

### ISSUE THREAD

**Issue by coderofsalvation** [megalon/pd-gui-examples#1]
Great stuff!
Btw. I noticed that I can 'fake' a standalone application by create a `.bat` or `.sh` file (windows/linux) with:

`path/to/pd.exe -open mypatch.pd -nogui`

This will for instance, open a a GEM-window, but not the patch- and console-window.
My question is:

> Did you find a similar way for displaying just the patch-window, but not the console-window?
That would easify shipping a one-window-patch-app to customers.

**Comment by megalon** [comment]
Thanks! 

I don't know of a way to launch pd without the console window, unfortunately.
I took a quick look through all of the launch args for pd and didn't see an argument for it either.
<https://github.com/pure-data/pure-data/blob/master/src/s_main.c>

If you figure it out, let me know!

**Comment by coderofsalvation** [comment]
Thanks! Likewise!
